<?php
	include ("include/header_nav.php");
?>
<main>
	<img id="about_us_image" src="images/about_us.jpg" width="550px">
	<div id="about_us_message">
		<h2>About Us</h2>
		<p>“In its fifth year, the Global Change Award has proven a great gateway for innovators to enter the fashion industry and transform it from the inside. The next big idea that will change the game can come from anyone anywhere. So, if you have an idea you believe in this is the place to go”, says Karl-Johan Persson, board member of the Fashionwave Foundation and CEO of Fashionwave Hennes & Mauritz AB.</p>
		<p>In other words, Fashionwave Foundation is open for ideas from all over the world. So far, the challenge has seen more than 14,000 entries from 182 countries. An interesting fact is that the challenge has become more global every year, with splendid ideas from emerging markets on the rise. For example, the number of entries originating from Africa and Asia has increased by almost 200 % and 90 % respectively between years 3 and 4. Furthermore, the ideas represent a broad range of exciting innovations — the winners from GCA 2019 range from the lab-made vegan leather, fibres made of nettles, a digital system to make products recyclable from scratch, children’s clothes that expand to a biodegradable toxic-free membrane for outdoor wear.</p>
		<p>To win the Global Change Award, the innovation should have the potential to make fashion circular and to scale. It should be sustainable and reduce, substitute, recycle or eliminate the use of the earth’s resources. Other criteria are a novelty, that the idea is economically sustainable and that the innovation team is committed to making a difference. Fashionwave Foundation initiated the challenge to find innovations that allow major change for the entire industry, and the winner can collaborate with whoever they want. Neither the non-profit Fashionwave Foundation nor Fashionwave Group take any equity or intellectual property rights in the innovations. The purpose of GCA is to influence the entire fashion industry, and in the end, this also means improving living conditions for people and communities globally. </p>
		<p>As a non-profit foundation, Fashionwave Foundation doesn’t have the same requirements of getting a certain return on investment within x years, as most private businesses do. This means that innovations that may seem risky and shaky can be selected as winners. Funding is a major challenge for innovators, especially in the circular economy, a pattern that is revealed through the enormous bank of entries GCA has received over the years. Fashionwave Foundation can really make a difference here and invest in and support these innovators, to increase their chances of entering the market. For sure there are a vast number of great ideas out there but access to capital, know-how and business support is scarce, and many great ideas never get to see the light of day. These ideas are the ones Global Change Award want to find, to give them the support needed to make a difference.</p>
		<p>As soon as the winners have been granted their awards at a ceremony in Stockholm, Sweden, they start the program – described by many previous winners as far more valuable than the cash grant. During this year the Fashionwave Foundation, Accenture and the KTH Royal Institute of Technology support the winners, taking them to Stockholm, New York and Hong Kong with the ambition to take their ideas to the next level, bringing them to scale and out on the market as quickly as possible, to maximize their impact on the industry.</p>
	</div>
</main>
<?php
	include ("include/footer.php");
?>